In [1]:
import numpy as np

In [2]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [7]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(5)

array([0.39728049, 0.10749938, 0.36191089, 0.37293234, 0.43497109])

In [10]:
np.random.randn(5)

array([-0.21598316, -0.8148413 ,  0.40022483,  0.02026181,  1.11792712])

In [11]:
np.random.randn(5,4)

array([[-2.60272646, -0.80439182,  0.20694343, -0.30555526],
       [ 0.05145116,  0.30210708, -0.09347582,  1.7881483 ],
       [-3.38053186,  0.39023535, -0.22666525, -0.55046716],
       [-0.602905  ,  0.10707842,  0.83087596,  0.63508131],
       [ 0.56273584, -0.56915648, -0.44887151,  0.24103464]])

In [12]:
np.random.randint(1,100)

59

In [13]:
np.random.randint(1,100,10)

array([12, 85, 12, 60, 80, 10, 67, 83, 20, 69])

In [14]:
np.random.randint(1,100,10)

array([55, 22, 49, 64, 25, 77, 98, 25, 76, 12])

In [15]:
np.random.randint(1,100,10)

array([52, 64,  1, 87, 26, 80, 62, 20, 68, 53])

In [16]:
np.random.randint(1,100)

91

In [17]:
np.random.randint(1,100,10)

array([75, 57, 60, 87, 30, 60, 82, 58, 95, 89])

In [18]:
arr = np.arange(25)

In [19]:
ranarr = np.random.randint(1,50,20)

In [20]:
ranarr

array([35, 15,  2, 35, 20, 33,  5,  2,  3,  2, 26, 45, 41, 39, 19,  3, 14,
       33, 25,  1])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr

array([35, 15,  2, 35, 20, 33,  5,  2,  3,  2, 26, 45, 41, 39, 19,  3, 14,
       33, 25,  1])

In [24]:
ranarr.max()

45

In [25]:
ranarr.min()

1

In [26]:
ranarr.argmax()

11

In [27]:
ranarr.argmin()

19

In [28]:
arr.shape

(25,)

In [29]:
ranarr.shape

(20,)

In [30]:
arr = arr.reshape(5,5)

In [31]:
arr.shape

(5, 5)

In [32]:
arr.dtype

dtype('int32')

In [33]:
ranarr.dtype

dtype('int32')

In [34]:
from numpy.random import randint

In [35]:
randint(1,100,10)

array([33, 50, 11,  6, 50, 57, 23, 70,  5, 68])

In [36]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
arr = np.arange(0,21)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [40]:
arr[8]

8

In [41]:
arr[3]

3

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
arr[:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[-1:]

array([20])

In [46]:
arr[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [48]:
arr[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [50]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [51]:
arr[0:5]=100

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [53]:
arr = np.arange(0,21)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [55]:
slice_of_arr = arr[0:6]

In [56]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [57]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_of_arr[:] = 99

In [59]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [61]:
arr_copy = arr.copy()

In [62]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [63]:
arr_copy[:] = 100

In [64]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [66]:
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [67]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr2d[2][1]

40

In [69]:
arr2d[2,1]

40

In [70]:
arr2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [71]:
arr2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [72]:
arr2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [73]:
arr = np.arange(1,11)

In [74]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
bool_arr = arr > 5

In [76]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [81]:
arr_2d = np.arange(0,50).reshape(10,5)

In [82]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [83]:
arr_2d[7:9,2:]

array([[37, 38, 39],
       [42, 43, 44]])

In [84]:
arr2d = np.zeros((9,10))

In [85]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
arr_length = arr2d.shape[1]

In [87]:
arr_length

10

In [88]:
arr_length = arr2d.shape[0]

In [89]:
arr_length

9

In [90]:
for i in range(arr2d.shape[0]):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [91]:
arr = np.arange(1,51).reshape(10,5)

In [92]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [93]:
for i in range(arr.shape[0]):
    arr[i] = i

In [94]:
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9]])

In [95]:
arr = np.arange(0,11)

In [96]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr += arr

In [98]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
arr * arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [100]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr+arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [102]:
arr/arr

C:\Users\awtqu\AppData\Local\Temp/ipykernel_3896/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [103]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [104]:
arr = arr/2

In [105]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
arr+100

array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.])

In [107]:
arr**arr


array([1.00000000e+00, 1.00000000e+00, 4.00000000e+00, 2.70000000e+01,
       2.56000000e+02, 3.12500000e+03, 4.66560000e+04, 8.23543000e+05,
       1.67772160e+07, 3.87420489e+08, 1.00000000e+10])

In [108]:
1/arr

C:\Users\awtqu\AppData\Local\Temp/ipykernel_3896/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [109]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [110]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr = np.arange(1,11).reshape(5,2)

In [114]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [119]:
arr[3:,:]

array([[ 7,  8],
       [ 9, 10]])